---
- name: 'master01'
  box: 'jgabriel/ubuntu-20.04'
  box_name: 'master01'
  box_version: "1.0"
  box_provider: 'virtualbox'
  hostname: 'master01'
  dir_host: '.'
  dir_guest: '/vagrant'
  cpu: '2'
  ram: '2048'
  disk: '30GB'
  vmgui: 'false'
  host_port: '1020' 
  guest_port: '443'
  file_provision: './provision/provision.sh'
  kubernetes_component: 'control-plane'

#- name: 'worker01'
#  box: 'jgabriel/ubuntu-20.04'
#  box_name: 'worker01'
#  box_version: "1.0"
#  box_provider: 'virtualbox'
#  hostname: 'worker01'
#  dir_host: '.'
#  dir_guest: '/vagrant'
#  cpu: '2'
#  ram: '2048'
#  disk: '30GB'
#  vmgui: 'false'
#  host_port: '1021' 
#  guest_port: '443'
#  file_provision: './provision/provision.sh'
#  kubernetes_component: 'worker-node'

#- name: 'worker02'
#  box: 'jgabriel/ubuntu-20.04'
#  box_name: 'worker01'
#  box_version: "1.0"
#  box_provider: 'virtualbox'
#  hostname: 'worker01'
#  dir_host: './shared_folder'
#  dir_guest: '/vagrant'
#  cpu: '2'
#  ram: '4096'
#  disk: '50GB'
#  vmgui: 'false'
#  host_port: '1022' 
#  guest_port: '443'
#  file_provision: './provision/provision.sh'
#  k8s_component: 'worker-node'
...